sudo: required
dist: bionic
python: "2.7.15"

stages:
  - name: script
    if: branch = main
  - name: deploy

jobs:
  include:
  - if: branch = main
    language: minimal
    env:
    - TEST=testme
  - if: branch = main
    language: minimal
    env:
    - TEST=branch_check
  allow_failures:
    - env: TEST=branch_check

script:
- echo $TEST
- echo $TRAVIS_BRANCH

deploy:
  provider: script
  script:
  - echo "deploy"
  branches:    # ← new!
    only:      # ← new!
      - main # ← new!
