sudo: required
dist: bionic
python: "2.7.15"

if: branch = main

stages:
  - name: test
  #- name: deploy

jobs:
  include:
  - stage: test
    language: minimal
    env:
    - TEST=testme
  - stage: test
    language: minimal
    env:
    - TEST=branch_check
  - stage: deploy
    script: skip
    deploy:
      provider: script
      on:
        branch:
          - main # ← new!
      script:
      - echo "deploy"
  allow_failures:
    - env: TEST=branch_check

script:
- echo $TEST
- echo $TRAVIS_BRANCH

