dist: bionic
python: "2.7.15"

if: branch = main

stages:
  - name: test
  - name: deploy

jobs:
  include:
  - stage: test
    language: minimal
    env:
    - TEST=testme
    stage: deploy
    script: skip
    deploy:
      provider: script
      on:
        branch:
          - main # ← new!
      script:
      - echo "deploy"
  - language: minimal
    env:
    - TEST=branch_check
  allow_failures:
    - env: TEST=branch_check

script:
- echo $TEST
- echo $TRAVIS_BRANCH
- echo -e "travis_fold:start:ABCDEF\033[33;1mGHIJKL\033[0m"
- echo 'CONTENTCONTECTCONTECT'
- echo -e "\ntravis_fold:end:ABCDEF\r"

